version: '3.8'
services:
  rails:
    build: .
    command: bash -c "rails s -b 0.0.0.0 | bundle exec sidekiq"
    container_name: rails_docker_sidekiq
    ports:
      - 3000:3000
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - HUB_URL=http://chrome:4444/wd/hub
    depends_on:
      - job_storage
      - db
      - chrome
  job_storage:
    image: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - rails_docker_sidekiq_redis_data:/var/lib/postgresql/data
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - rails_docker_sidekiq_data:/var/lib/postgresql/data
  chrome:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
      - 5900:5900
volumes:
  rails_docker_sidekiq_data:
  rails_docker_sidekiq_redis_data: